name: mechanical_components

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/mechanical_components.yml'
      - '.github/workflows/freecad_export.py'
      - '.github/workflows/openscad_preview.sh'
      - 'Mechanical/Design/**'

permissions:
  contents: write
  pages: write
  id-token: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  generate-artifacts:
    name: freecad export
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        component:
        - 'FRONTPANEL-SHEET-BU16'
        - 'FRONTPANEL-SHEET-EF44'
        - 'FRONTPANEL-SHEET-PBF4'
        - 'FRONTPANEL-SHEET-TEK2'
        - 'FRONTPANEL-SHEET-VSN0'
        - 'FRONTPANEL-SHEET-VSN1'
        - 'FRONTPANEL-SHEET-VSN1-R'
        - 'FRONTPANEL-SHEET-VSN2'
        - 'INSERT-FADER'
        - 'INSERT-M1.6x2.5x3'
        - 'INSERT-M1.6x2.5x4'
        - 'KNOB-TEK2'
        - 'MAGNET-D3x13'
        - 'MAGNET-SQ3'
        - 'THT-BUTTON'
        - 'THT-HALL-SWITCH'
        - 'THT-ENC'
        - 'THT-ENDLESSPOT'
        - 'THT-FADER'
        - 'THT-LONGFADER'
        - 'THT-POT'
        - 'SMT-VSN1-DISPLAY'
        - 'SMT-CONN-POGO'
        - 'SMT-CONN-BATTERY'
        - 'PLASTIC-BUSHING-POT'
        - 'PLASTIC-BUSHING-POT-TEK2'
        - 'PLASTIC-CANVAS'
        - 'PLASTIC-CAP-BUTTON'
        - 'PLASTIC-CAP-FADER'
        - 'PLASTIC-KNOB-ENC'
        - 'PLASTIC-KNOB-POT'
        - 'PLASTIC-LIGHTPIPE'
        - 'PLASTIC-LIGHTPIPE-ISOLATOR'
        - 'PLASTIC-LOW-PROFILE-KEYCAP'
        - 'PLASTIC-MAGNET-COVER'
        - 'PLASTIC-MAPMODE'
        - 'PLASTIC-SPACER'
        - 'PLASTIC-VSN1-BUTTON'
        - 'PLASTIC-VSN1-DISPLAY-INTERFACE'
        - 'PLASTIC-TEK2-KNOB-INTERFACE'
        - 'RUBBER-FOOT'
        - 'SCREW-M1.6x8'
        - 'SCREW-M1.6x16'
        - 'SPACER'
        
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb x11vnc
        sudo apt-get  install snapd
        sudo snap install freecad
        sudo apt-get install -y openscad
        Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
        sleep 10  # Give Xvfb some time to start
        x11vnc -display :99 -nopw -listen localhost -xkb -ncache 10 -ncache_cr -forever > /dev/null 2>&1 &

    - name: Run GUI application
      continue-on-error: true
      run: |
        ls        
        export DISPLAY=:99
        timeout 1m freecad --hidden ./Mechanical/Design/${{ matrix.component }}/${{ matrix.component }}.FCStd ./.github/workflows/freecad_export.py step pdf

    - name: Install conda, pythonocc and do the conversion
      run: |
        CONDA_INSTALL_DIR="$HOME/miniconda3"

        # Download and install Miniconda
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        bash miniconda.sh -b -p "$CONDA_INSTALL_DIR"
        rm miniconda.sh

        # Add Miniconda to PATH
        export PATH="$CONDA_INSTALL_DIR/bin:$PATH"

        # Initialize conda
        conda init bash

        # Print Miniconda version
        conda --version

        conda install -c conda-forge pythonocc-core=7.7.2 --yes

        conda --version
        python ./.github/workflows/pythonocc_step_to_stl.py

    - name: Generate Preview PNG
      run: |
        ./.github/workflows/openscad_preview.sh

    - name: Stop x11vnc
      run: pkill x11vnc

    - name: Set Date
      run: echo "action_date=$(date +'%Y-%m-%d-%H%M')" >> $GITHUB_ENV
        
    - name: Copy reference files
      run: |
        cp Mechanical/Design/${{ matrix.component }}/reference_* temp/ || true

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: "result_${{ matrix.component }}_${{ env.action_date }}"
        path: temp/*.*

  deploy-results:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: generate-artifacts    
    steps:
      - uses: actions/checkout@v2
        with:
          ref: preview

      - name: Download reports' artifacts
        uses: actions/download-artifact@v4
        with:
          path: download

      - name: Collecting files
        run: |

          # Create the temp folder if it doesn't exist
          mkdir -p Preview/Mechanical

          # Loop through each subdirectory in the download folder
          for subdirectory in download/*; do
              # Check if it is a directory
              if [ -d "$subdirectory" ]; then
                  # Copy the contents of the subdirectory to the temp folder
                  cp -r "$subdirectory"/* "Preview/Mechanical/"
              fi
          done

      - name: Commit the files
        run: |        
          git config --global user.name ${{ github.actor }}
          git config --global user.email ${{ github.actor }}@users.noreply.github.com  
          git add Preview/*
          git commit -m "BOT ${{ github.workflow }} ${{ github.sha }}"
          git push

  deploy-assets:
    if: github.ref == 'refs/heads/master'
    needs: deploy-results 
    environment:
      name: mechanical_deployment
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Download reports' artifacts
        uses: actions/download-artifact@v4
        with:
          path: download

      - name: Collecting files
        run: |

          # Create the temp folder if it doesn't exist
          mkdir -p temp

          # Loop through each subdirectory in the download folder
          for subdirectory in download/*; do
              # Check if it is a directory
              if [ -d "$subdirectory" ]; then
                  # Copy the contents of the subdirectory to the temp folder
                  cp -r "$subdirectory"/* "temp/"
              fi
          done

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: './temp/'
          name: mechanical_deployment

      - name: Deploy to GitHub Pages
        id: mechanical_deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: mechanical_deployment
